# Generated by Django 6.0.7 on 2026-07-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federacion_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpase',
            name='nota_liberacion',
            field=models.TextField(blank=True, help_text='Comentario opcional del club de origen al liberar (ej: valor del pase, condiciones).'),
        ),
        migrations.AlterField(
            model_name='solicitudpase',
            name='estado',
            field=models.CharField(choices=[('pendiente_liberacion', 'Esperando liberación del club de origen'), ('pendiente', 'Pendiente (federación)'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
