# Generated by Django 6.0.7 on 2026-07-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federacion_app', '0002_solicitudpase_nota_liberacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='numero_carnet',
            field=models.CharField(blank=True, help_text='Número de carnet de la federación, si ya lo tiene.', max_length=30),
        ),
        migrations.AddField(
            model_name='persona',
            name='requiere_carnet',
            field=models.BooleanField(default=False, help_text='Marcar si hay que tramitarle el carnet.'),
        ),
    ]
