# Generated by Django 6.0.7 on 2026-07-30 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federacion_app', '0003_persona_numero_carnet_persona_requiere_carnet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('temporada', models.CharField(help_text='Ej: 2026, Apertura 2026', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-temporada', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derechos_federativos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fondo_seleccion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carnet', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de cobro'), ('cobrado', 'Cobrado')], default='pendiente', max_length=20)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cobro', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones_torneo', to='federacion_app.club')),
                ('cobrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscripciones_cobradas', to=settings.AUTH_USER_MODEL)),
                ('inscrito_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_torneo', to='federacion_app.persona')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='federacion_app.torneo')),
            ],
            options={
                'ordering': ['-fecha_inscripcion'],
            },
        ),
    ]
