# Generated by Django 6.0.7 on 2026-07-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federacion_app', '0004_torneo_inscripciontorneo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripciontorneo',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscripciontorneo',
            name='pagado',
            field=models.BooleanField(default=False, help_text='Marcar cuando el club efectivamente pagó.'),
        ),
    ]
