# Generated by Django 6.0.7 on 2026-07-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federacion_app', '0005_inscripciontorneo_fecha_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='escudo',
            field=models.ImageField(blank=True, null=True, upload_to='escudos_clubes/'),
        ),
    ]
