# Generated by Django 6.0.7 on 2026-07-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federacion_app', '0006_club_escudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='precio_carnet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='torneo',
            name='precio_derechos_federativos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='torneo',
            name='precio_fondo_seleccion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
