# Generated by Django 6.0.7 on 2026-08-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federacion_app', '0007_torneo_precio_carnet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='rol_tecnico',
            field=models.CharField(blank=True, choices=[('dt', 'DT'), ('ayudante', 'Ayudante técnico'), ('pf', 'Preparador físico'), ('delegado', 'Delegado'), ('otro', 'Otro')], help_text="Solo si tipo='tecnico'", max_length=10),
        ),
    ]
