# Generated by Django 6.0.7 on 2026-08-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federacion_app', '0008_persona_rol_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentopersona',
            name='tipo',
            field=models.CharField(choices=[('dni', 'DNI'), ('certificado_medico', 'Certificado médico'), ('foto_carnet', 'Foto carnet'), ('autorizacion_fichaje', 'Autorización de fichaje firmada (Form. 08)'), ('otro', 'Otro')], max_length=30),
        ),
    ]
