# Generated by Django 6.0.7 on 2026-08-03 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federacion_app', '0009_alter_documentopersona_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentacionFormulario12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_firmado', models.FileField(blank=True, null=True, upload_to='formularios12_firmados/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de firma/aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentaciones_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='federacion_app.categoria')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presentaciones_formulario12', to='federacion_app.club')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presentaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('jugadores', models.ManyToManyField(blank=True, related_name='presentaciones_como_jugador', to='federacion_app.persona')),
                ('tecnicos', models.ManyToManyField(blank=True, related_name='presentaciones_como_tecnico', to='federacion_app.persona')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presentaciones_formulario12', to='federacion_app.torneo')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
