# Generated by Django 6.0.7 on 2026-08-04 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federacion_app', '0010_presentacionformulario12'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('amarilla', 'Amarilla'), ('azul_indirecta', 'Azul indirecta'), ('azul_directa', 'Azul directa')], max_length=20)),
                ('fecha_partido', models.DateField()),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('cargada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarjetas_cargadas', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarjetas', to='federacion_app.club')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='federacion_app.persona')),
                ('torneo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarjetas', to='federacion_app.torneo')),
            ],
            options={
                'ordering': ['-fecha_partido'],
            },
        ),
        migrations.CreateModel(
            name='SancionTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tarjeta', models.CharField(choices=[('amarilla', 'Amarilla'), ('azul_indirecta', 'Azul indirecta'), ('azul_directa', 'Azul directa')], max_length=20)),
                ('numero_ocurrencia', models.PositiveSmallIntegerField(help_text='1ra, 2da, 3ra... vez que se llega a este umbral')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cumplido', 'Fecha cumplida')], default='pendiente', max_length=20)),
                ('comprobante_pago', models.FileField(blank=True, null=True, upload_to='comprobantes_sanciones/')),
                ('fecha_generada', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanciones', to='federacion_app.club')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanciones', to='federacion_app.persona')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanciones_resueltas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_generada'],
                'constraints': [models.UniqueConstraint(fields=('persona', 'tipo_tarjeta', 'numero_ocurrencia'), name='unica_sancion_por_umbral')],
            },
        ),
    ]
