# Generated by Django 6.0.7 on 2026-08-04 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federacion_app', '0011_tarjeta_sanciontarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('delegado', 'Delegado de club'), ('federacion', 'Administrador de federación'), ('consejo_disciplina', 'Consejo de disciplina')], max_length=20),
        ),
        migrations.CreateModel(
            name='SancionDisciplinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('informe', models.FileField(blank=True, null=True, upload_to='informes_disciplina/')),
                ('fecha_sancion', models.DateField()),
                ('cantidad_fechas', models.PositiveSmallIntegerField(blank=True, help_text='Cantidad de fechas de suspensión, si corresponde', null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cumplida', 'Cumplida')], default='activa', max_length=20)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('cargada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanciones_disciplinarias_cargadas', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sanciones_disciplinarias', to='federacion_app.club')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanciones_disciplinarias', to='federacion_app.persona')),
            ],
            options={
                'ordering': ['-fecha_sancion'],
            },
        ),
    ]
