# Generated by Django 6.0.7 on 2026-08-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federacion_app', '0012_alter_usuario_rol_sanciondisciplinaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanciondisciplinaria',
            name='cantidad_anios',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Cantidad de años de suspensión, si corresponde en vez de fechas', null=True),
        ),
    ]
