# Generated by Django 6.0.7 on 2026-08-04 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federacion_app', '0013_sanciondisciplinaria_cantidad_anios'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('reglamento', 'Reglamento'), ('formulario', 'Formulario'), ('circular', 'Circular'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('archivo', models.FileField(upload_to='institucional/')),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_institucionales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('destinatarios', models.ManyToManyField(blank=True, help_text='Dejar vacío para enviar a todos los clubes.', related_name='notificaciones', to='federacion_app.club')),
                ('leida_por', models.ManyToManyField(blank=True, related_name='notificaciones_leidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
