# Generated by Django 6.0.7 on 2026-08-04 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federacion_app', '0014_documentoinstitucional_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionAcuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_acuse', models.DateTimeField(blank=True, null=True)),
                ('respuesta', models.TextField(blank=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('acusado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acuses_notificaciones', to='federacion_app.club')),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acuses', to='federacion_app.notificacion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('notificacion', 'club'), name='un_acuse_por_club_por_notificacion')],
            },
        ),
    ]
