# Generated by Django 6.0.7 on 2026-08-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federacion_app', '0015_notificacionacuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionacuse',
            name='visto_por_federacion',
            field=models.BooleanField(default=False),
        ),
    ]
