# Generated by Django 6.0.7 on 2026-08-05 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federacion_app', '0016_notificacionacuse_visto_por_federacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripciontorneo',
            name='fichaje_nuevo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inscripciontorneo',
            name='jugador_libre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='notificaciones/'),
        ),
        migrations.AddField(
            model_name='persona',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si está desactivado, no puede jugar ni ser seleccionado en planillas.'),
        ),
        migrations.AddField(
            model_name='solicitudpase',
            name='tipo_pase',
            field=models.CharField(blank=True, choices=[('definitivo', 'Definitivo'), ('prestamo', 'Préstamo')], help_text="Solo aplica cuando tipo='pase'", max_length=20),
        ),
        migrations.AddField(
            model_name='torneo',
            name='precio_fichaje_nuevo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='torneo',
            name='precio_jugador_libre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_partido', models.DateField()),
                ('cantidad', models.PositiveSmallIntegerField(default=1, help_text='Goles convertidos en ese partido')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('cargado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goles_cargados', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goles', to='federacion_app.club')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goles', to='federacion_app.persona')),
                ('torneo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goles', to='federacion_app.torneo')),
            ],
            options={
                'ordering': ['-fecha_partido'],
            },
        ),
    ]
