# Generated by Django 6.0.7 on 2026-08-05 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federacion_app', '0017_inscripciontorneo_fichaje_nuevo_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vinculo',
            name='unico_vinculo_activo_por_persona',
        ),
        migrations.AddField(
            model_name='club',
            name='club_madre',
            field=models.ForeignKey(blank=True, help_text="Si este club es una segunda entidad de otro (ej: 'Real Madrid Azul' bajo 'Real Madrid'), elegí acá el club madre.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucursales', to='federacion_app.club'),
        ),
        migrations.AddField(
            model_name='vinculo',
            name='es_principal',
            field=models.BooleanField(default=True, help_text='Entre los vínculos activos de una persona, cuál se muestra como club de referencia.'),
        ),
    ]
