# Generated by Django 6.0.7 on 2026-08-13 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federacion_app', '0018_remove_vinculo_unico_vinculo_activo_por_persona_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolRecibido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_partido', models.DateField()),
                ('cantidad', models.PositiveSmallIntegerField(default=1, help_text='Goles recibidos en ese partido')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('cargado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goles_recibidos_cargados', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goles_recibidos', to='federacion_app.club')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goles_recibidos', to='federacion_app.persona')),
                ('torneo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goles_recibidos', to='federacion_app.torneo')),
            ],
            options={
                'ordering': ['-fecha_partido'],
            },
        ),
    ]
