# Generated by Django 6.0.7 on 2026-08-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federacion_app', '0019_golrecibido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpase',
            name='tipo_pase',
            field=models.CharField(blank=True, choices=[('definitivo', 'Definitivo'), ('prestamo', 'Préstamo'), ('libre', 'Libre')], help_text='Solo aplica en un pase entre clubes.', max_length=20),
        ),
    ]
