# Generated by Django 6.0.7 on 2026-08-16 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federacion_app', '0020_alter_solicitudpase_tipo_pase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoPunitorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('monto_sugerido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descripcion', models.TextField(blank=True, help_text='Texto de motivo por defecto, editable al momento de aplicarlo.')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Punitorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=20)),
                ('comprobante_pago', models.FileField(blank=True, null=True, upload_to='comprobantes_punitorios/')),
                ('fecha_generado', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('cargado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='punitorios_cargados', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='punitorios', to='federacion_app.club')),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punitorios', to='federacion_app.conceptopunitorio')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punitorios_resueltos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_generado'],
            },
        ),
    ]
