# Generated by Django 6.0.7 on 2026-08-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federacion_app', '0021_conceptopunitorio_punitorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculo',
            name='rol_tecnico',
            field=models.CharField(blank=True, choices=[('dt', 'DT'), ('ayudante', 'Ayudante técnico'), ('pf', 'Preparador físico'), ('delegado', 'Delegado'), ('otro', 'Otro')], help_text="Solo si tipo='tecnico', en este vínculo puntual.", max_length=10),
        ),
        migrations.AddField(
            model_name='vinculo',
            name='tipo',
            field=models.CharField(choices=[('jugador', 'Jugador'), ('tecnico', 'Cuerpo técnico')], default='jugador', max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='activo',
            field=models.BooleanField(default=False, help_text='Se activa solo cuando se aprueba su primer Formulario 12. Si está desactivado, no puede jugar ni ser seleccionado en planillas.'),
        ),
    ]
