# Generated by Django 6.0.7 on 2026-08-22 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federacion_app', '0022_vinculo_rol_tecnico_vinculo_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('delegado', 'Delegado de club'), ('federacion', 'Administrador de federación'), ('consejo_disciplina', 'Consejo de disciplina'), ('arbitro', 'Árbitro')], max_length=20),
        ),
        migrations.CreateModel(
            name='InformeArbitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_partido', models.DateField()),
                ('contenido', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='informes_arbitros/')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('visto_por_federacion', models.BooleanField(default=False)),
                ('arbitro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informes_arbitrales', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='federacion_app.categoria')),
                ('club_local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='informes_como_local', to='federacion_app.club')),
                ('club_visitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='informes_como_visitante', to='federacion_app.club')),
                ('torneo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='federacion_app.torneo')),
            ],
            options={
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='respuestas_informes_arbitros/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('visto_por_arbitro', models.BooleanField(default=False)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='federacion_app.informearbitro')),
                ('respondido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_a_arbitros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
