# Generated by Django 6.0.7 on 2026-09-24 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federacion_app', '0023_alter_usuario_rol_informearbitro_respuestainforme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('activa', models.BooleanField(default=True)),
                ('categorias_habilitadas', models.ManyToManyField(blank=True, help_text='Categorías que pueden jugar en esta cancha. Dejar vacío = todas las categorías.', related_name='canchas_habilitadas', to='federacion_app.categoria')),
            ],
            options={
                'verbose_name_plural': 'Canchas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadCancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='federacion_app.cancha')),
            ],
            options={
                'verbose_name_plural': 'Disponibilidades de cancha',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.CharField(help_text='Ej: Fecha 5, Cuartos de final', max_length=50)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('arbitro', models.ForeignKey(blank=True, limit_choices_to={'rol': 'arbitro'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_arbitrados', to=settings.AUTH_USER_MODEL)),
                ('cancha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos', to='federacion_app.cancha')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos', to='federacion_app.categoria')),
                ('club_local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos_local', to='federacion_app.club')),
                ('club_visitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos_visitante', to='federacion_app.club')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos_creados', to=settings.AUTH_USER_MODEL)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos', to='federacion_app.torneo')),
            ],
            options={
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
