# Generated by Django 6.0.7 on 2026-09-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federacion_app', '0024_cancha_disponibilidadcancha_partido'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='duracion_minutos',
            field=models.PositiveSmallIntegerField(default=60, help_text='Duración de cada partido de esta categoría, en minutos. Se usa para calcular los turnos disponibles al programar el fixture.'),
        ),
    ]
